https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv
https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv


```
X = 
H = tf.keras.layers.Dense(5, activaion='swish')(X)
H = tf.keras.layers.Dense(3, activaion='swish')(X)
H = tf.keras.layers.Dense(3, activaion='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
```




In [ ]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

# 보스턴 집값 예측

In [ ]:
# 1. 과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)

# 독립변수, 종속변수 분리
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [ ]:
# 2. 모델의 구조를 만듭니다.
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [ ]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# 3. 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 19.6856
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 21.3000
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 21.2513
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 21.0800
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 22.1380
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 19.5925
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 21.1480
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 24.4654
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 20.4924
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 20.0260


In [ ]:
# 4. 모델을 이용합니다
print(model.predict(독립[:5]))
print(종속[:5])

[[29.844225]
 [24.93726 ]
 [31.985214]
 [30.88816 ]
 [30.851767]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


# 아이리스 품종 분류

In [ ]:
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

# 원핫인코딩
인코딩 = pd.get_dummies(아이리스)

# 독립변수, 종속변수
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [ ]:
# 2. 모델의 구조를 만듭니다.
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [ ]:
# 3. 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 1s 3ms/step - loss: 1.0570 - accuracy: 0.2667
Epoch 2/100
5/5 [==============================] - 0s 2ms/step - loss: 0.9642 - accuracy: 0.3600
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 0.9046 - accuracy: 0.6867
Epoch 4/100
5/5 [==============================] - 0s 2ms/step - loss: 0.8536 - accuracy: 0.8733
Epoch 5/100
5/5 [==============================] - 0s 4ms/step - loss: 0.8116 - accuracy: 0.8000
Epoch 6/100
5/5 [==============================] - 0s 3ms/step - loss: 0.7742 - accuracy: 0.9000
Epoch 7/100
5/5 [==============================] - 0s 5ms/step - loss: 0.7409 - accuracy: 0.8200
Epoch 8/100
5/5 [==============================] - 0s 5ms/step - loss: 0.7103 - accuracy: 0.8733
Epoch 9/100
5/5 [==============================] - 0s 3ms/step - loss: 0.6818 - accuracy: 0.8400
Epoch 10/100
5/5 [==============================] - 0s 5ms/step - loss: 0.6561 - accuracy: 0.9000
Epoch 11/100
5/5 [===========

In [ ]:
# 4. 모델을 이용합니다.
print(model.predict(독립[0:5]))
print(종속[0:5])

[[9.9862278e-01 7.6118612e-04 6.1608228e-04]
 [9.9749643e-01 1.3737443e-03 1.1297871e-03]
 [9.9769360e-01 1.2824548e-03 1.0239449e-03]
 [9.9698335e-01 1.7588488e-03 1.2578212e-03]
 [9.9865866e-01 7.5253734e-04 5.8885384e-04]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
